name: easycoutcol
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  animate_do: ^4.2.0
  change_app_package_name: ^1.5.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_riverpod: ^2.6.1
  go_router: ^15.0.0
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  riverpod: ^2.6.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
